value: value-for-profile-override
all-value: value-for-all-ms
---
spring:
  config:
    activate:
      on-profile: dev

value: value-dev
dev-all-ms-value: value-dev-for-all-ms
---
spring:
  config:
    activate:
      on-profile: prod

value: value-prod
dev-all-ms-value: value-prod-for-all-ms
