two-value: ms-two-all-profile-value
---
spring:
  config:
    activate:
      on-profile: dev
dev-two-value: ms-two-dev-profile-value
---
spring:
  config:
    activate:
      on-profile: prod
dev-two-value: ms-prod-dev-profile-value
