one-value: ms-one-all-profile-value
---
spring:
  config:
    activate:
      on-profile: dev
dev-one-value: ms-one-dev-profile-value
---
spring:
  config:
    activate:
      on-profile: prod
dev-one-value: ms-one-prod-profile-value
